### PR TITLE
Issue #6 - Only output failures

### PR DESCRIPTION
**Pull request by michaelBenin**
- Fix: Task now uses config options, verbose to set output failures
- Add: Updated docs, read options in task, verbose option

### CODE REVIEW

**Comment by xzyfer** [comment]
+:100:

**Comment by ariya** [comment]
Looks good but can you fix the commit so that it doesn't change the formatting of the copyright header? It's just confusing, especially looking at the diff.

**Comment by michaelBenin** [comment]
Not a problem.

**Comment by ariya** [comment]
I don't see the reason why the whole needs to have an indentation change (4-space to 2-space).

**Comment by michaelBenin** [comment]
Would you like me to add a jsbeautifier task to the build of this project with the configuration of 4 spaces? 
I'll make the indentation 4 spaces today.

**Comment by ariya** [comment]
For a small code like this, I don't think it's necessary to involve an automatic formatter.

**Comment by phadej** [comment]
Is this PR still pending something, can it be merged?

**Pull request merged**
